[package]
name = "rig_errors"
version = "0.1.0"
edition = "2021"

[dependencies]
rig_span = { path = "../rig_span" }
rig_intern = { path = "../rig_intern" }
rig_session = { path = "../rig_session" }
owo-colors = "3.5.0"