[package]
name = "rig_session"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rig_ast = { path = "../rig_ast" }
rig_intern = { path = "../rig_intern" }
owo-colors = "3.5.0"
