[package]
name = "rig_span"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rig_intern = { path = "../rig_intern" }
rig_session = { path = "../rig_session" }
parking_lot = "0.12.1"
